### ISSUE TITLE
Tasmota has spanish firmware

### ISSUE THREAD

**Issue by ascillato** [reloxx13/SonWEB#17]
Hi,

I really like SonWEB. It is very nice.

I suggest to add spanish (ES) as option for selecting the firmware due to Sonoff Tasmota has also a spanish version.

Thanks!

**Comment by reloxx13** [comment]
Heya,

thanks for the feedback :)

Im sorry but i cannot add ES firmware because Theo does not upload/provide a spanish binary.

Sonweb is looking on the [releases page](https://github.com/arendst/Sonoff-Tasmota/releases) in the automatic modus for binaries per git api.

As soon as he add it, ill add it, too 👍

**Comment by ascillato** [comment]
Great!
Thanks!
