### ISSUE TITLE
How to upload full firmware?

### ISSUE THREAD

**Issue by ascillato** [reloxx13/SonWEB#18]
On the upload menu, SonWEB ask for both FULL and MINIMAL firmware.

If I want just to upload FULL firmware, SonWEB reply that I did not select any MINIMAL.

And, If I put both, SonWEB upload just the MINIMAL to my Sonoff.

How I can upload the FULL Firmware?

**Comment by reloxx13** [comment]
You should upload both since the new tasmota firmware is to big to upload it to the device without the minimal version.

The Updater should upate the minimal and then the full in the progress.

**Comment by ascillato** [comment]
Sorry. I don't understand.

If I compile a sonoff.ino.bin and upload it from the sonoff webserver goes ok.

Why I need to compile a minimal and a full version, to upload the minimal and then the full to the device if I don't need that from the sonoff menu?

**Comment by reloxx13** [comment]
Heya,

Please read here:
https://github.com/arendst/Sonoff-Tasmota/wiki/Upgrade#functionality-vs-firmware-size-vs-ota
https://github.com/arendst/Sonoff-Tasmota/wiki/What's-New#20180110---5111a---otamagic

If you dont want to compile a minimal fw each time, you can just compile one and use it again and again.

**Comment by ascillato** [comment]
Ah, Ok.

The minimal version make some memory space so a bigger program can be uploaded by OTA.

So I didn't have problems before with the firmware upload from the sonoff's webserver, just because my build wasn't so big.

Now, I understand.

Thanks.

I tested the upload using SonWEB and works amazing! :)

**Comment by reloxx13** [comment]
yep. it depents on what you did enable in the user_config.h and in the future its possible that even with all disabled you need to use a minimal before. i think its better to be safe and update the minimal before the full fw rather then brick the device and need to re-flash by usb flasher :S

**Comment by TimelessNL** [comment]
But what if a user build their own firmware and keeps the size below <50% so minimal update is not required? It would make sense to make the minimal image optional in such a case.

I tried to put my software image in both the minimal/full field and TasmoAdmin did update my Tasmota devices without any issue. So that great but still unnecessary in my eyes.

Still I find it strange that I don't see any logging that it first applies the Minimal image and the the Full image. But I could be mistaken?
