### ISSUE TITLE
Show Timer active Status in sonweb

### ISSUE THREAD

**Issue by eeprom23** [reloxx13/SonWEB#86]
Hi, Can you show a Status ( red Point or Text Timer) on  Sonweb startpage when one or more Timers active on sonoff TASMOTA device ?

Thank‘s

**Comment by reloxx13** [comment]
heya,

active as "one or more timer is set" or active as "timer is on/triggered now" ? :)

**Comment by reloxx13** [comment]
i checked the status 0 response and unfortunately their is no timer info in the response for now.

this would lead to a 2nd request to the devices because i have to request the timers.
but adding more requests to a device is not good, because the esp cannot handle alot of requests.

if theo would add the timer infos to the status request, this is doable, but for now its not :(

**Comment by eeprom23** [comment]
I have make a New issues on the TASMOTA Site .

https://github.com/arendst/Sonoff-Tasmota/issues/2385
